const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const stream = require('stream');

router.post('/', (req, res) => {
  const { name, subject, score, maxScore, grade, date } = req.body;

  const doc = new PDFDocument({ margin: 50 });

  const bufferStream = new stream.PassThrough();
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=${subject}-report.pdf`);

  doc.pipe(bufferStream);

  // Title
  doc.fontSize(24).fillColor('#4B0082').text('CourseHub Assessment Report', {
    align: 'center',
    underline: false,
  });

  doc.moveDown(1.5);

  // Details
  doc.fontSize(14).fillColor('#000').text(`Name: ${name}`);
  doc.text(`Subject: ${subject}`);
  doc.text(`Score: ${score} / ${maxScore}`);
  doc.text(`Grade: ${grade}`);
  doc.text(`Date: ${date}`);

  doc.moveDown(2);
  doc.fontSize(10).fillColor('gray').text('Generated by CourseHub • ' + new Date().toLocaleDateString(), {
    align: 'center',
  });

  doc.end();
  bufferStream.pipe(res);
});

module.exports = router;
